spring.application.name=tv_score
tmdb.api.url=https://api.themoviedb.org/3
tmdb.api.key=b345f996c9aea46e0e1c151745d351c2
tmdb.api.language=pt-PT
server.port=8080
server.address=0.0.0.0

spring.datasource.url=jdbc:mysql://10.106.75.22:3306/TVscore?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver